#!/bin/sh
#
# Copyright (c) 2009 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Add icons to the system icons
XDG_ICON_RESOURCE="`which xdg-icon-resource 2> /dev/null`"
if [ ! -x "$XDG_ICON_RESOURCE" ]; then
  echo "Error: Could not find xdg-icon-resource" >&2
  exit 1
fi
for icon in "/usr/share/copyit/mmsprojects-copyit-"*.png; do
  size="${icon##*/mmsprojects-copyit-}"
  "$XDG_ICON_RESOURCE" install --size "${size%.png}" "$icon" "mmsprojects-copyit"
done
"$XDG_ICON_RESOURCE" install --size "${size%.png}" "$icon" "mmsprojects-copyit"

# Add an entry to the system menu
XDG_DESKTOP_MENU="`which xdg-desktop-menu 2> /dev/null`"
UPDATE_MENUS="`which update-menus 2> /dev/null`"
if [ ! -x "$XDG_DESKTOP_MENU" ]; then
  echo "Error: Could not find xdg-desktop-menu" >&2
  exit 1
fi
"$XDG_DESKTOP_MENU" install /usr/share/applications/mmsprojects-copyit.desktop

if [ -x "$UPDATE_MENUS" ]; then
  update-menus
fi
